### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Half-Shot** [BlankParenthesis/visualiser#1]
Hey there, I was wondering if you had planned to publish this under a licence? The code looks useful and I'd like to adapt it for a (FOSS) project of mine, but it would require me to know what terms the code is offered under?

Thanks!

**Comment by BlankParenthesis** [comment]
It seems I have not yet attached a license to this code, but I am perfectly happy to apply one. Given your project is FOSS, I imagine something like GPL should be fine? If so, I'll add that.

**Comment by Half-Shot** [comment]
Yeah, whatever you fancy (I see you use GPL-2 in other places, which is perfectly easy to follow)

**Comment by BlankParenthesis** [comment]
I have added a GPL-2 license, I wish you the best with your project  👍
